import Head from 'next/head';
import Header from './Components/Header';
import Carousel, { CarouselItem } from './Components/Carousel/Carousel';
import MenuButton from './Components/HeaderComponents/NavigationBarComponents/MenuButton';


export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Header/> */}
        <div>
          <Carousel>
            <CarouselItem>Item1</CarouselItem>
          </Carousel>
          {/* Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi quibusdam maxime quisquam consectetur possimus, dolorum suscipit reiciendis debitis atque tempora ab alias doloremque quidem facilis eius. Rerum id quo officiis! */}
        </div>
      </main>
    </>
  );
}
