import Head from 'next/head'
// import { Inter } from 'next/font/google'
import Button from '@mui/material/Button'
// import styles from '@/styles/Home.module.css'
import UpperNav from './UpperNav';
// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col'>
        <UpperNav/>
      </main>
    </>
  )
}
