import Head from 'next/head'
import Header from './Components/Header'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <div>
          <p>
            Whether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay 
            when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not 
            there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is
            Whether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay 
            when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not 
            there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is
            Whether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay 
            when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not 
            there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is
            Whether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay 
            when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not 
            there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is
            Whether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay 
            when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not 
            there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is
            Whether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay 
            when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not 
            there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is
            Whether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay 
            when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not 
            there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is
            Whether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay 
            when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not 
            there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is
            Whether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay 
            when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not 
            there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is
            Whether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay 
            when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not 
            there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is
            Whether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay 
            when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not 
            there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is
            Whether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay 
            when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not 
            there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is scrollingWhether or not there is a little delay when the user is
          </p>
        </div>
      </main>
    </>
  )
}
